image:
    - Visual Studio 2017
    - Visual Studio 2019    

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\comms_champion
shallow_clone: true             

platform:
    - x64
    - x86

configuration:
    - Debug
    - Release

matrix:
    fast_finish: false
        
install:
    - call script\appveyor_install.bat
    - set PATH=%PATH%;%QTDIR%\bin

build_script:
    - mkdir build.%PLATFORM%.%CONFIGURATION%.%TOOLCHAIN%
    - cd build.%PLATFORM%.%CONFIGURATION%.%TOOLCHAIN%
    - cmake .. -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G "NMake Makefiles" -DCC_QT_DIR=%QTDIR% -DCMAKE_INSTALL_PREFIX=%cd%/install 
    - nmake install

test_script:
    - ctest 


